#!/usr/bin/env python3
"""
Import air quality data (Indice ATMO) per commune.

Downloads the daily ATMO index from the Atmo France WFS service,
computes the yearly mean index per commune, and generates a SQL
seed file for Supabase.

Source: https://data.gouv.fr/datasets/indice-de-la-qualite-de-lair-quotidien-par-commune-indice-atmo

Usage:
    pip install pandas requests
    python3 scripts/import_atmo.py

Output: supabase/seed_atmo.sql
"""

import io
import os
import sys
import time

import pandas as pd
import requests

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(PROJECT_DIR, "data", "atmo")
OUTPUT_PATH = os.path.join(PROJECT_DIR, "supabase", "seed_atmo.sql")
INSEE_CODES_PATH = os.path.join(DATA_DIR, "insee_codes.txt")
CACHE_PATH = os.path.join(DATA_DIR, "ind_atmo.csv")

WFS_URL = (
    "https://data.atmo-france.org/geoserver/ind/ows"
    "?service=WFS&request=GetFeature&TypeNames=ind_atmo_2021&outputformat=csv"
)


def escape_sql(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def get_known_insee_codes():
    path = os.path.join(PROJECT_DIR, "data", "insee_codes.txt")
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        return set(line.strip() for line in f if line.strip())


def normalize_insee(code):
    """Ensure INSEE code is 5 characters with leading zeros."""
    s = str(code).strip()
    if len(s) < 5 and s.isdigit():
        s = s.zfill(5)
    return s


def download_wfs():
    """Download ATMO commune data from the data.gouv.fr WFS endpoint."""
    os.makedirs(DATA_DIR, exist_ok=True)

    if os.path.exists(CACHE_PATH):
        print(f"  [cached] {CACHE_PATH}")
        return pd.read_csv(CACHE_PATH, dtype={"code_zone": str}, low_memory=False)

    print(f"  Downloading from WFS ...")
    t0 = time.time()

    r = requests.get(
        WFS_URL,
        timeout=600,
        stream=True,
        headers={"Accept-Encoding": "gzip, deflate"},
    )
    r.raise_for_status()

    with open(CACHE_PATH, "wb") as f:
        for chunk in r.iter_content(chunk_size=1024 * 1024):
            f.write(chunk)

    elapsed = time.time() - t0
    size_mb = os.path.getsize(CACHE_PATH) / (1024 * 1024)
    print(f"  → {size_mb:.1f} MB downloaded in {elapsed:.0f}s")

    df = pd.read_csv(CACHE_PATH, dtype={"code_zone": str}, low_memory=False)
    print(f"  → {len(df):,} rows")
    return df


def process_data(df, known_insee):
    """Aggregate daily ATMO index to yearly mean per commune."""
    print(f"\n=== Processing ===")
    print(f"  Input: {len(df):,} rows")

    df = df[df["type_zone"].str.lower() == "commune"].copy()
    print(f"  After type_zone=commune filter: {len(df):,} rows")

    df = df.dropna(subset=["code_zone", "code_qual"])
    df["code_zone"] = df["code_zone"].apply(normalize_insee)
    df["code_qual"] = pd.to_numeric(df["code_qual"], errors="coerce")
    df = df.dropna(subset=["code_qual"])

    if known_insee is not None:
        df = df[df["code_zone"].isin(known_insee)]
        print(f"  After filtering to known communes: {len(df):,} rows")

    stats = (
        df.groupby("code_zone")["code_qual"]
        .agg(["mean", "count"])
        .reset_index()
    )
    stats.columns = ["code_insee", "indice_moyen", "nb_jours"]
    stats["indice_moyen"] = stats["indice_moyen"].round(2)

    print(f"  Communes with data: {len(stats):,}")
    print(f"  Mean index: {stats['indice_moyen'].mean():.2f}")
    print(f"  Median days of data: {stats['nb_jours'].median():.0f}")

    print(f"\n  Distribution:")
    for label, lo, hi in [
        ("Bonne (≤2.0)", 0, 2.0),
        ("Moyenne (2.0-3.0)", 2.0, 3.0),
        ("Dégradée (3.0-4.0)", 3.0, 4.0),
        ("Mauvaise (>4.0)", 4.0, 7.0),
    ]:
        count = len(stats[(stats["indice_moyen"] > lo) & (stats["indice_moyen"] <= hi)])
        if lo == 0:
            count = len(stats[stats["indice_moyen"] <= hi])
        pct = count * 100 / len(stats) if len(stats) > 0 else 0
        print(f"    {label:25s}: {count:6d} communes ({pct:.1f}%)")

    return stats


def generate_sql(stats):
    """Generate SQL seed file."""
    print(f"\n=== Generating SQL ===")
    BATCH = 2000

    rows = []
    for _, r in stats.iterrows():
        rows.append((r["code_insee"], float(r["indice_moyen"]), int(r["nb_jours"])))

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("-- ============================================\n")
        f.write("-- Ou Atterir - Air quality data (Indice ATMO)\n")
        f.write("-- Source: Atmo France WFS (data.gouv.fr)\n")
        f.write("-- Generated by scripts/import_atmo.py\n")
        f.write("-- ============================================\n\n")
        f.write("BEGIN;\n\n")
        f.write("DELETE FROM commune_air_quality;\n\n")

        for i in range(0, len(rows), BATCH):
            batch = rows[i : i + BATCH]
            f.write(
                "INSERT INTO commune_air_quality (code_insee, indice_moyen, nb_jours) VALUES\n"
            )
            vals = []
            for code_insee, indice, nb in batch:
                vals.append(f"({escape_sql(code_insee)},{indice},{nb})")
            f.write(",\n".join(vals))
            f.write(
                "\nON CONFLICT (code_insee) DO UPDATE SET\n"
                "  indice_moyen = EXCLUDED.indice_moyen,\n"
                "  nb_jours = EXCLUDED.nb_jours;\n\n"
            )

            if (i + BATCH) % 20000 == 0 or i + BATCH >= len(rows):
                pct = min(100, (i + BATCH) * 100 // len(rows))
                print(f"  Writing... {pct}%")

        f.write("-- Refresh materialized view\n")
        f.write("REFRESH MATERIALIZED VIEW commune_air_summary;\n\n")
        f.write("COMMIT;\n")

    size_mb = os.path.getsize(OUTPUT_PATH) / (1024 * 1024)
    print(f"\n{'='*50}")
    print(f"Done!")
    print(f"  Output:     {OUTPUT_PATH}")
    print(f"  File size:  {size_mb:.1f} MB")
    print(f"  Rows:       {len(rows)}")
    print(f"  Communes:   {stats['code_insee'].nunique()}")
    print(f"\nTo import into Supabase:")
    print(f"  1. Apply migration: supabase db push")
    print(f"  2. Then run this seed file:")
    print(f"     psql '<CONNECTION_STRING>' -f supabase/seed_atmo.sql")


def main():
    known_insee = get_known_insee_codes()
    if known_insee:
        print(f"Filtering to {len(known_insee):,} known communes")

    print("=== Step 1/3: Download WFS data ===")
    df = download_wfs()

    print("\n=== Step 2/3: Aggregate ===")
    stats = process_data(df, known_insee)

    print("\n=== Step 3/3: Generate SQL ===")
    generate_sql(stats)


if __name__ == "__main__":
    main()
