#!/usr/bin/env python3
"""
Push DVF stats to Supabase via REST API.
Reads the seed SQL generated by import_dvf.py and inserts in batches.
"""

import json
import os
import re
import sys
import time

import requests

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
SEED_PATH = os.path.join(PROJECT_DIR, "supabase", "seed_dvf.sql")

SUPABASE_URL = os.environ.get("VITE_SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("VITE_SUPABASE_ANON_KEY", "")

if not SUPABASE_URL or not SUPABASE_KEY:
    try:
        from dotenv import load_dotenv
        load_dotenv(os.path.join(PROJECT_DIR, ".env.local"))
    except ImportError:
        pass
    if not SUPABASE_URL:
        SUPABASE_URL = os.environ.get("VITE_SUPABASE_URL", "")
    if not SUPABASE_KEY:
        SUPABASE_KEY = os.environ.get("VITE_SUPABASE_ANON_KEY", "")

if not SUPABASE_URL or not SUPABASE_KEY:
    env_path = os.path.join(PROJECT_DIR, ".env.local")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line.startswith("VITE_SUPABASE_URL="):
                    SUPABASE_URL = line.split("=", 1)[1]
                elif line.startswith("VITE_SUPABASE_ANON_KEY="):
                    SUPABASE_KEY = line.split("=", 1)[1]

if not SUPABASE_URL or not SUPABASE_KEY:
    print("Error: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set")
    sys.exit(1)

REST_URL = f"{SUPABASE_URL}/rest/v1/commune_dvf_stats"
HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "resolution=merge-duplicates",
}

BATCH_SIZE = 500
ROW_RE = re.compile(r"\('([^']+)',(\d+),'([^']+)',(\d+),(\d+)\)")


def parse_seed_sql(path):
    """Extract rows from the seed SQL file."""
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            for m in ROW_RE.finditer(line):
                rows.append({
                    "code_insee": m.group(1),
                    "year": int(m.group(2)),
                    "type_local": m.group(3),
                    "nb_mutations": int(m.group(4)),
                    "prix_m2_median": int(m.group(5)),
                })
    return rows


def main():
    if not os.path.exists(SEED_PATH):
        print(f"Error: {SEED_PATH} not found. Run import_dvf.py first.")
        sys.exit(1)

    print(f"Parsing {SEED_PATH}...")
    rows = parse_seed_sql(SEED_PATH)
    print(f"  {len(rows):,} rows to insert")

    session = requests.Session()
    session.headers.update(HEADERS)

    inserted = 0
    errors = 0
    t0 = time.time()

    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i:i + BATCH_SIZE]

        try:
            resp = session.post(REST_URL, json=batch, timeout=30)
            if resp.status_code in (200, 201):
                inserted += len(batch)
            else:
                errors += len(batch)
                if errors <= 2500:
                    print(f"  Error {resp.status_code}: {resp.text[:300]}")
        except Exception as e:
            errors += len(batch)
            if errors <= 2500:
                print(f"  Request error: {e}")

        done = inserted + errors
        if done % 10000 < BATCH_SIZE or i + BATCH_SIZE >= len(rows):
            elapsed = time.time() - t0
            pct = min(100, done * 100 // len(rows))
            rate = inserted / elapsed if elapsed > 0 else 0
            print(f"  {pct}% | {inserted:,} inserted, {errors:,} errors | {rate:.0f} rows/s")

    elapsed = time.time() - t0
    print(f"\nDone in {elapsed:.1f}s")
    print(f"  Inserted: {inserted:,}")
    print(f"  Errors:   {errors:,}")

    if errors == 0:
        print("\nAll data pushed successfully!")
        print("Note: You still need to run 'REFRESH MATERIALIZED VIEW commune_market_tension;'")
        print("in the Supabase SQL editor to update the tension levels.")


if __name__ == "__main__":
    main()
